- hosts: all
  become: true
  become_user: root
  remote_user: ged
  roles:
    - role: comman
  tags: commancheck

- hosts: webserver
  become: true
  become_user: root
  remote_user: ged
  roles:
    - role: webserver
  tags: webs

- hosts: all
  become: yes
  become_user: root
  roles: 
    - role: useradd
  tags: useradd

- hosts: stat
  become: yes
  become_user: root
  remote_user: ged
  roles:
    - role: stat
  tags: stat
