---
- name: disk durumun bak
  shell: "df -h /"
  args:
    executable: "/bin/bash"
  register: disk

- name: disl çıktısı
  debug:
    msg: "{{ disk.stdout_lines }}"


- name: debian rsyslog kurma
  apt:
    name: rsyslog
    state: present
  
- name: rsyslog service restart
  service: "name=rsyslog state=restarted"
 

