apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1
  labels:
    app: front-end      
spec:
  template:
    metadata: 
      name: mypod
      labels: 
        app: front-end
    spec:
      containers:
      - name: mynginx
        image: nginx        
  replicas: 3
  selector: 
    matchLabels: 
      app: front-end
        

