apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydeployment2
  name: mydeployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydeployment2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydeployment2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      nodeSelector: 
        size: large  
status: {}
