apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mynginx
  name: webapp-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: mynginx
  type: NodePort
status:
  loadBalancer: {}
